config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos,   only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'one star':   '1_star',
    'two stars':   '2_stars',
    'three stars': '3_stars',
    'four stars':  '4_stars',
    'five stars':  '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  
  mount_uploader :picture, PictureUploader

  
  
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  
  geocoded_by      :address
  after_validation :geocode

  validates :name,         presence: true, length: { minimum: 3}
  validates :address,      presence: true
  validates :description,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

    def comment_params
      params.require(:comment).permit(:message, :rating)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end

  private

    def photo_params
      params.require(:photo).permit(:caption, :picture)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index 
    @places = Place.paginate(page: params[:page], per_page: 5)
  end

  def new
    @place = Place.new
  end

  def create 
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed!', status: :forbidden
    end

  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed!', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed!', status: :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  private

    def place_params
      params.require(:place).permit(:name, :address, :description, :photo)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show 
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Munchin</title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Munchin', root_path, class: 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>   
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>   
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h2>Edit Your Place</h2>
  <br />

  <%= simple_form_for @place do |f| %>
    <div class="form-inputs">
      <%= f.input :name,    label: false, required: false, 
                            autofocus: true %>
      <%= f.input :address, label: false, required: false %>
      <%= f.input :description, label: false, required: false, 
                             class: 'text-field' %>
    </div>
    <br />

    <div class="form-actions">
      <%= f.button :submit, "Submit", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3 class="caption">Find the best pizza</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Let the environment set your mood</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Looking for fresh coffee?</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<%= will_paginate @places %>

<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <div class="row">
      <div class="col-12 col-lg-4 offset-lg-1">
        <h1><%= link_to place.name, place_path(place) %></h1>
        <hr />
        <i><%= place.address %></i><br /><br />
        <p><%= place.description %></p><br />

        <% if place.user.present? %>
          <small><%= place.user.email %></small>
        <% end %>

        <% if place.comments.present? %>
          <div class="col-12 blockquote-container">
            <blockquote>
              <% if place.comments.last.humanized_rating.present? %>
                <b><%= place.comments.last.humanized_rating %></b> -
              <% end %>
              <%= place.comments.last.message %>
              <small><%= place.comments.last.user.email %></small>
            </blockquote>
          </div>
        <% end %>

      </div>

      <div class="clear"></div>

      <div class="col-12 col-lg-7 index-photo text-center">
        <% if place.photos.present? %>
          <%= image_tag place.photos.last.picture, class: 'd-block img-fluid' %>
        <% end %>
      </div>
    </div>


  </div>
<% end %>

<%= will_paginate @places %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h2>Enter your place details</h2>
  <br />

  <%= simple_form_for @place do |f| %>
    <div class="form-inputs">
      <%= f.input :name,    label: false, required: false, 
                             placeholder: "Name", autofocus: true %>
      <%= f.input :address, label: false, required: false, 
                             placeholder: "Address" %>
      <%= f.input :description, label: false, required: false, 
                             placeholder: "Description", class: 'text-field' %>
    </div>
    <br />

    <div class="form-actions">
      <%= f.button :submit, "Create", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="row">
    <div class="col-12 col-lg-4">
      <h1><%= @place.name %></h1>
      <i><%= @place.address %></i>
      <br><br>
      <p><%= @place.description %></p>
    </div>  

    <div class="place-buttons text-right col-12 col-lg-8 ">
      <% if current_user %>
        <div class="row">
          <div class="col-12 col-lg-3 offset-lg-2">
            <button type="button" class="btn btn-primary add-comment-button" data-toggle="modal" data-target="#comment-modal">
              Leave a Comment
            </button>
          </div>
          <div class="col-12 col-lg-3">
            <button type="button" class="btn btn-primary add-photo-button" data-toggle="modal" data-target="#photo-modal">
              <i class="fa fa-plus-circle"></i>
              Add a Photo
            </button>
          </div>
          <% if current_user == @place.user %>
            <div class="col-12 col-lg-2">
              <%= link_to 'Edit', edit_place_path(@place),  
                 class: 'btn btn-primary' %>
            </div>
            <div class="col-12 col-lg-2">
              <%= link_to 'Delete', place_path(@place), method: :delete, 
                           data: { confirm: "are you sure you want to delete this place?"}, 
                           class: 'btn btn-danger delete-place-button' %>
            </div>
          <% end %>
       </div>
      <% else %>
        <%= link_to 'Log in', new_user_session_path %> to leave a comment
      <% end %>
    </div>
  </div>

  <div class="clear"></div>

  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>

    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBl3Y8YAf8R7VVk1apGCWjuV7GZFZ6gecw&callback=initMap">
    </script>

  <div id="map"></div>

  <% end %>


  <div class="row photo-row">
    <% @place.photos.each do |photo| %>
      <div class="col-12 col-lg-4 photo-container">
        <div class="place-photo text-center">
          <% if photo.picture.present? %>
            <%= image_tag photo.picture %>
          <% end %>
        </div>
        <div class="place-photo-caption text-center">
          <%= photo.caption %>
        </div>
      </div>   
    <% end %>
  </div>

</div>

<div class="clear"></div>

<div class="booyah-box col-10 offset-1">

  <h1 class="float-left">Comments</h1>

  <div class="clear"></div>
  <hr />

  <div class="row">
    <% @place.comments.each do |comment| %>
      <div class="col-12 col-sm-6 ">
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
</div>


<!-- Photo Modal -->
<div class="modal fade" id="photo-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :caption, label: false, placeholder: "Caption" %>
        </div>
        <div class="picture">
          <%= f.file_field :picture %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add Photo", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Comment Modal -->
<div class="modal fade" id="comment-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          Comment
          <%= f.input :message, label: false%>
          Rating
          <%= f.input :rating, label: false, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add a Comment", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="row">
    <div class="col-12 col-lg-2 offset-lg-1 ">
      <%= image_tag 'user.png', class: "user-icon" %>
    </div>

    <div class="col-12 col-lg-9 text-center">
      <h1><%= @user.email %></h1>
      <hr>
      <h3>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4><%= @user.comments.count %> total comments</h4>
      <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
  </div>
  <div class="clear"></div>
</div>

<br><br>
<h1 class="text-center">My Comments</h1>
<br><br>
<div class="col-10 offset-1">
  <div class="row">
    <% @user.comments.each do |comment| %>
      <div class="col-12 col-sm-6 ">
        <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place), class: "user-comment-link" %></h2>
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %> 
  </div>
</div>  

<div class="clear"></div>
<br><br><hr>
<h1 class="text-center">My Places</h1>
<br><br>

<% @user.places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <div class="row">
      <div class="col-12 col-lg-4 offset-lg-1">
        <h1><%= link_to place.name, place_path(place) %></h1>
        <hr />
        <i><%= place.address %></i><br /><br />
        <p><%= place.description %></p><br />
        <% if place.user.present? %>
          <small><%= place.user.email %></small>
        <% end %>
        <% if place.comments.present? %>
          <div class="col-12 blockquote-container">
            <blockquote>
              <% if place.comments.last.humanized_rating.present? %>
                <b><%= place.comments.last.humanized_rating %></b> -
              <% end %>
              <%= place.comments.last.message %>
              <small><%= place.comments.last.user.email %></small>
            </blockquote>
          </div>
        <% end %>
      </div>
      <div class="clear"></div>
      <div class="col-12 col-lg-7 index-photo text-center">
        <% if place.photos.present? %>
          <%= image_tag place.photos.last.picture, class: 'd-block img-fluid' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>